### ISSUE TITLE
Duration is ignored after first render

### ISSUE THREAD

**Issue by dantman** [jossmac/react-blink#2]
The setInterval is only registered inside of componentDidMount. This means that any change to props.duration will not change the duration of setInterval.

Either componentWillReceiveProps or componentWillUpdate should be used to recreate the interval if the duration changes.

**Comment by jossmac** [comment]
Hi @dantman,

Thanks for your comment! I'm open to PR's if you're offering :)

**Comment by JedWatson** [comment]
@jossmac @dantman just added this with #3, it's a simpler implementation using setTimeout instead of setInterval so the next timeout is always set with the current value of the `interval` prop.
